require("plugins.gruvbox-material")

require("plugins.alpha")
require("plugins.auto-session")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.neoscroll")
require("plugins.telescope")
require("plugins.tree")
require("plugins.treesitter")

require("plugins.options")
