name: Update flake.lock

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

    - name: Update flake.lock
      uses: DeterminateSystems/update-flake-lock@da03c0f078bc4b2c37ee4f7e072d34bf8f188bb3 # v29
      with:
        inputs: >-
          home-manager
          llm-agents
          neovim-config
          nixpkgs
          nixpkgs-unstable
        commit-msg: Update flake.lock
        pr-title: Update flake.lock
